In [1]:
import numpy as np
import pygame
from matplotlib import pyplot as plt
import random
from math import sqrt

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html


In [2]:
class CMeans:
    def __init__(self, dataset, n_clusters=3, m=1.2, k=.9):
        self.dataset = dataset
        self.n_clusters = n_clusters
        self.m = m
        self.k = k
        self.max_n_iter = 100
        self.tolerance = .01
        self.dist = np.zeros((self.dataset.shape[0], self.n_clusters))
        self.centroids = np.zeros((self.n_clusters, self.dataset.shape[1]))
        self.u = np.array([np.random.uniform(0, 1) for i in range(self.n_clusters)] for j in range(self.dataset.shape[0]))
        print(self.centroids)

    def distribute_data(self):
        self.dist = np.array([[self.get_dist2(i, j) for i in self.centroids] for j in self.dataset])
        self.u = (1 / self.dist) ** (2 / (self.m - 1))
        self.u = self.u / self.u.sum(axis=1)[:, None]

    def recalculate_centroids(self):
        self.centroids = (self.u.T).dot(self.dataset) / self.u.sum(axis=0)[:, None]

    def fit(self):
        iter = 1
        while iter < self.max_n_iter:
            prev_centroids = np.copy(self.centroids)
            self.recalculate_centroids()
            self.distribute_data()
            if max([self.get_dist2(i, k) for i, k in zip(self.centroids, prev_centroids)]) < self.tolerance:
                break
            iter += 1

    def get_labels(self):
        l1 = self.u.max(axis=1)
        l2 = self.u.argmax(axis=1)
        l3 = np.array([i + 1 for i in l2])
        return np.array([i if j > self.k else 0 for i, j in zip(l3, l1)])

    def get_dist2(self, list1, list2):
        return sum((i - j) ** 2 for i, j in zip(list1, list2))

In [12]:
X = np.array([[1, 2, 3], [4, 5, 6]])

In [13]:
test = CMeans(X, 3, 1.2, .9)
test.fit()
pred = test.get_labels()
colors = np.array(['#000000', '#377eb8', '#ff7f00', '#4daf4a'])
plt.figure()
plt.scatter(dataset[:, 0], dataset[:, 1], c=colors[pred])
plt.show()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


TypeError: unsupported operand type(s) for *: 'generator' and 'int'